version: '2'
services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/ppap6/server-go:preview
    ports:
      - "8080:8080"
    volumes:
      - ./config.ini:/root.config.ini
    restart: always