name: preview
on:
  push:
    branches:
      - master
    pull_request:

jobs:
#  # 检查
#  check:
#    name: check
#    runs-on: ubuntu-latest
#    steps:
#      # 获取代码仓库
#      - uses: actions/checkout@v2
#
#      # 安装Go环境
#      - name: set up go
#      - uses: actions/setup-go@v2
#        with:
#        go-version:'^1.13.1'
#
#      # vet 静态检测
#      - name: vet
#        run: |
#          go vet ./...


  build:
    name: build
    runs-on: ubuntu-latest
    # needs: [check]   # 先允许check失败，因为不知道github action的失败判定逻辑
    steps:
       # 获取代码仓库
      - uses: actions/checkout@v2

      - name: docker build
        run: |
          # 编译并推送至阿里云
          # todo 现在只有一个版本的镜像，无法回滚；考虑在release分支做多版本镜像用于回滚
          docker login --username=${{ secrets.aliyun_registry_user }} --password=${{ secrets.aliyun_registry_pw }} registry.cn-hangzhou.aliyuncs.com
          docker build -t ${{ secrets.aliyun_registry }}:preview .
          docker push ${{ secrets.aliyun_registry }}:preview

  deply:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_TOKEN: ${{ secrets.aliyun_key }}
    steps:
      - name: update_server
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p $SSH_PATH
          echo -e "$SSH_TOKEN" > "$SSH_PATH/id_rsa"
          chmod 600 "$SSH_PATH/id_rsa"
          chmod 600 "$SSH_PATH/known_hosts"
          ssh-keyscan -t rsa ${{ secrets.aliyun_server_addr}} >> "$SSH_PATH/known_hosts"
          ssh dev@${{ secrets.aliyun_server_addr}} "cd /home/dev/vhost/ppap-go-previe && docker-compose up -d"